image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/python:3.11

stages:
  - test

variables:
  SCYLLA_HOST: scylla
  SCYLLA_PORT: 9042
  SCYLLA_KEYSPACE: bec_atlas

services:
  - name: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/scylladb/scylla:latest
    alias: scylla

# before_script:
#   - pip install ./backend
#   - python -u ./backend/bec_atlas/utils/setup_database.py


test:
  stage: test
  script:
    - pip install ./backend[dev]
    - pytest --skip-docker --random-order ./backend/tests
