image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/python:3.11

stages:
  - test

variables:
  SCYLLA_HOST: scylla
  SCYLLA_PORT: 9042
  SCYLLA_KEYSPACE: test_bec_atlas

services:
  - name: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/scylladb/scylla:latest
    alias: scylla

before_script:
  - pip install ./backend
  - python -u ./backend/ci/setup_database.py


test:
  stage: test
  script:
    - python -c "from cassandra.cluster import Cluster; cluster = Cluster(['scylla']); session = cluster.connect(); session.set_keyspace('test_bec_atlas');"
