name: Full CI
on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      BEC_CORE_BRANCH:
        description: 'Branch of BEC Core to install'
        required: false
        type: string

permissions:
  pull-requests: write

jobs:
  check_pr_status:
    uses: ./.github/workflows/check_pr.yml

  formatter:
    needs: check_pr_status
    if: needs.check_pr_status.outputs.branch-pr == ''
    uses: ./.github/workflows/formatter.yml


  unit-test-backend:
    needs: [check_pr_status, formatter]
    if: needs.check_pr_status.outputs.branch-pr == ''
    uses: ./.github/workflows/pytest.yml
    with:
      BEC_CORE_BRANCH: ${{ inputs.BEC_CORE_BRANCH || 'main' }}
      BEC_ATLAS_BRANCH: ${{ inputs.BEC_ATLAS_BRANCH || github.head_ref || github.sha }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  unit-test-frontend:
    needs: [check_pr_status, formatter]
    if: needs.check_pr_status.outputs.branch-pr == ''
    uses: ./.github/workflows/fe_unit_test.yml
    with:
      BEC_ATLAS_BRANCH: ${{ inputs.BEC_ATLAS_BRANCH || github.head_ref || github.sha }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
